{
    'name': 'Real Estate Management',
    'version': '1.0',
    'category': 'Real Estate',
    'summary': 'Manage properties, sales, leases, tenants, and agents',
    'description': """Real Estate module to manage properties, tenants, leases, sales, and agents.""",
    'author': 'Quicksol Technolgies',
    'website': 'https://quicksol.ca',
    'depends': ['base'],
    'data': [
        'security/real_estate_security.xml',
        'security/ir.model.access.csv',
        'data/property_type_data.xml',
        'views/property_views.xml',
        'views/agent_views.xml',
        'views/lease_views.xml',
        'views/sale_views.xml',
        'views/tenant_views.xml',
        'views/real_estate_menus.xml',
    ],
    'installable': True,
    'auto_install' : False,
    'application': True,
}